version: '3'

services:
  flaskapp:
    container_name: flaskapp
    restart: always
    build: ./api
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 app:app

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flaskapp


# https://towardsdatascience.com/how-to-deploy-ml-models-using-flask-gunicorn-nginx-docker-9b32055b3d0